### ISSUE TITLE
Unknown command "go_to_website"

### ISSUE THREAD

**Issue by BarelyPlaying** [gravelBridge/AutoGPT-Web-Interaction#5]
Hi there,

I'm not sure why, but the command you showed in the screenshot doesn't seem to be recognized, even though I cloned the repo, zipped it, put it in my plugins folder, and allowed it on my plugins list. 

Any ideas?

Thank you

logs:

Input:no, please use command "go_to_website"
SYSTEM:  Human feedback: no, please use command "go_to_website"
 THOUGHTS:  To get the URLs for popular videos on Youtube, I will use the `get_hyperlinks` command on the Youtube homepage.
REASONING:  The Youtube homepage is likely to contain links to some of the most popular videos on the platform, so using `get_hyperlinks` on this page will allow me to extract those URLs.
PLAN:
-  Use the `go_to_website` command to navigate to the Youtube homepage, and then use the `get_hyperlinks` command to extract the URLs for some popular videos.
CRITICISM:  Some of the URLs returned by `get_hyperlinks` may not actually lead to videos, so I must be sure to filter out any unrelated links.
NEXT ACTION:  COMMAND = go_to_website ARGUMENTS = {'url': 'https://www.youtube.com/'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y

**Comment by bryanjohns** [comment]
When starting auto gpt, is `Auto-Web-Interaction-Plugin` being shown as one of the plugins that is loaded? Something like this: 
```
Plugins found: 4
--------------------
  Auto-Web-Interaction-Plugin: 0.1.0 - Auto-GPT Web Interaction Plugin: Interact with websites.   << ---- this one
  Bing-Search-Plugin: 0.1.0 - This plugin performs Bing searches using the provided query.
  autogpt-random-values: 0.1.0 - Enable Auto-GPT with the power of random values.
  autogpt-wikipedia-search: 0.1.0 - Wikipedia search integrations.
```

**Comment by BarelyPlaying** [comment]
no, it isn't:

  autogpt-notion: 0.1.0 - Notion API integrations using notion-sdk-py
  News-Search-Plugin: 0.1.0 - This plugin searches the latest news using the provided query and the newsapi aggregator
  autogpt-wikipedia-search: 0.1.0 - Wikipedia search integrations.
  AutoGPT-Zapier: 0.1.0 - AutoGPT Zapier Webhooks integration.
Welcome back!  Would you like me to return to being Browser?

**Comment by gravelBridge** [comment]
Did you install all the requirements? Also what version of autogpt are you running on?

**Comment by BarelyPlaying** [comment]
I followed the instruction guide,I should have everything. I'm on 0.3.0.

**Comment by BarelyPlaying** [comment]
Ah, I solved the issue. I had compressed the web interaction folder into a rar file, not a zip file. fair enough.
